@url = 
@stage = v1
@id = aa

########################################################################################
###
### GET
### Get all todos
###
########################################################################################
GET {{url}}/{{stage}}/todo


########################################################################################
###
### POST
### Create new todo
### Body:
###  name - {string} - Name of new todo item
###  tag - {string} - Tag for todo item
###  summary - {string} - Summary of todo item
########################################################################################
POST {{url}}/{{stage}}/todo
Content-Type: application/json

{
    "name": "Mohammed - create tasks for everyone",
    "tag": "xby2do",
    "summary": "Create tasks for everyone to go through aws setup instructions."
}


########################################################################################
###
### GET
###  Get todo based on ID in route
### Route:
###  id - {string} - Guid of todo item
########################################################################################
GET {{url}}/{{stage}}/todo/{{id}}


########################################################################################
###
### PUT
### Create new todo
### Body:
###  name - {string} - Name of new todo item
###  tag - {string} - Tag for todo item
###  summary - {string} - Summary of todo item
###  dueDate - {string} - Due date for todo item
###  done - {string} - Mark todo as 'done'. Values "true" or "false" only
########################################################################################
PATCH {{url}}/{{stage}}/todo/{{id}}
Content-Type: application/json

{
    "dueDate": "2020-07-10",
    "done": "true"
}